version: "2"
services:
  data:
    image: alpine
    hostname: data
    command: sh
    volumes:
      - /tmp
      - /opt/lattice/bin
      - /var/log
  xorg:
    image: gitai/xorg
    container_name: xorg
    hostname: xorg
    privileged: true
    read_only: true
    restart: always
    user: root
    environment:
      - DISPLAY=:0
    tmpfs:
      - /var/log
    volumes:
      - /home/user/workspace
    volumes_from:
      - data
  dbus:
    image: dengleros/dbus
    container_name: dbus
    hostname: dbus
    read_only: true
    restart: always
    volumes:
      - /var/lib/dbus
      - /var/run/dbus
      - /home/user/.dbus
    volumes_from:
      - data
  desktop:
    image: gitai/xfce4-desktop
    container_name: desktop
    hostname: desktop
    restart: unless-stopped
    environment:
      - DISPLAY=:0
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    volumes_from:
      - xorg
#volumes:
#  latticeos-tmp:
#  latticeos-varlibdbus:
#  latticeos-varrundbus:
#  latticeos-homeuserdbus:
#  latticeos-home: